import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = fileURLToPath(new URL('..', import.meta.url))
const specPath = join(repoRoot, 'spec/dist/openapi.json')

const spec = JSON.parse(readFileSync(specPath, 'utf8'))
const componentSchemas = spec.components?.schemas ?? {}

const HEADER = [
  '// DO NOT EDIT — generated by scripts/generate-backend.js from spec/dist/openapi.json.',
  '// Источник истины: spec/main.tsp. Любые правки перезапишутся при `npm run generate`.',
  '',
]

function inlineSchema(schema, stack = []) {
  if (schema && typeof schema === 'object' && typeof schema.$ref === 'string') {
    const ref = schema.$ref
    if (ref.startsWith('#/components/schemas/')) {
      const name = ref.slice('#/components/schemas/'.length)
      if (stack.includes(name)) {
        throw new Error(`Cyclic $ref in contract: ${[...stack, name].join(' -> ')}`)
      }
      const target = componentSchemas[name]
      if (!target) {
        throw new Error(`Unknown schema ref: ${ref}`)
      }
      return inlineSchema(target, [...stack, name])
    }
    throw new Error(`Unsupported $ref: ${ref}`)
  }
  if (Array.isArray(schema)) {
    return schema.map((item) => inlineSchema(item, stack))
  }
  if (schema && typeof schema === 'object') {
    const result = {}
    for (const [key, value] of Object.entries(schema)) {
      if (key === '$ref') continue
      result[key] = inlineSchema(value, stack)
    }
    return result
  }
  return schema
}

function parametersSchema(parameters) {
  const required = parameters.filter((p) => p.required).map((p) => p.name)
  const properties = {}
  for (const p of parameters) {
    properties[p.name] = inlineSchema(p.schema)
  }
  const schema = { type: 'object', properties }
  if (required.length > 0) {
    schema.required = required
  }
  return schema
}

function fastifyPath(path) {
  return path.replace(/\{([^}]+)\}/g, ':$1')
}

export function generateBackend() {
  const operations = []

  for (const [path, methods] of Object.entries(spec.paths ?? {})) {
    for (const [method, operation] of Object.entries(methods)) {
      if (!['get', 'post', 'put', 'delete', 'patch'].includes(method)) continue

      const parameters = operation.parameters ?? []
      const pathParameters = parameters.filter((p) => p.in === 'path')
      const queryParameters = parameters.filter((p) => p.in === 'query')

      const schema = {}
      if (pathParameters.length > 0) {
        schema.params = parametersSchema(pathParameters)
      }
      if (queryParameters.length > 0) {
        schema.querystring = parametersSchema(queryParameters)
      }
      const bodySchema = operation.requestBody?.content?.['application/json']?.schema
      if (bodySchema) {
        schema.body = inlineSchema(bodySchema)
      }
      const responses = {}
      for (const [code, response] of Object.entries(operation.responses ?? {})) {
        const responseContent = response.content?.['application/json']?.schema
        if (responseContent) {
          responses[code] = inlineSchema(responseContent)
        }
      }
      if (Object.keys(responses).length > 0) {
        schema.response = responses
      }

      operations.push({
        operationId: operation.operationId,
        method,
        path: fastifyPath(path),
        schema,
      })
    }
  }

  operations.sort((a, b) => `${a.method} ${a.path}`.localeCompare(`${b.method} ${b.path}`))

  const outDir = join(repoRoot, 'backend/src/gen')
  mkdirSync(outDir, { recursive: true })

  const schemaLines = ['export const schemas = {']
  for (const op of operations) {
    const key = `${op.operationId}Schema`
    schemaLines.push(`  ${key}: ${JSON.stringify(op.schema, null, 2).replace(/\n/g, '\n  ')},`)
  }
  schemaLines.push('}')

  writeFileSync(
    join(outDir, 'schemas.js'),
    [...HEADER, ...schemaLines, ''].join('\n'),
  )

  const routeLines = ['export default async function registerRoutes(app) {']
  for (const op of operations) {
    const schemaArg = `{ schema: schemas.${op.operationId}Schema }`
    routeLines.push(`  app.${op.method}('${op.path}', ${schemaArg}, handlers.${op.operationId})`)
  }
  routeLines.push('}')

  writeFileSync(
    join(outDir, 'routes.js'),
    [
      ...HEADER,
      "import { handlers } from '../handlers/index.js'",
      "import { schemas } from './schemas.js'",
      '',
      ...routeLines,
      '',
    ].join('\n'),
  )

  return operations.length
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const count = generateBackend()
  console.log(`Backend: сгенерировано ${count} операций в backend/src/gen/`)
}
